apiVersion: apps/v1

kind: Deployment
metadata:
  name: tab
spec:
  selector:
    matchLabels:
      app: tab
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: tab
        tier: backend
        track: stable
  
    spec:
      containers:
      - image: horcle/nlptab
        name: tab
        ports:
        - containerPort: 8000 
        volumeMounts:
        - name: volume
          mountPath: "/data/test"
  
      volumes:
      - name: volume
        hostPath:
          path: "/data/test"

