apiVersion: apps/v1

kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: es
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: es
        tier: backend
        track: stable
  
    spec:
      containers:
      - image: horcle/es
        name: es
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: volume
          mountPath: "/data/test"
  
      volumes:
      - name: volume
        hostPath:
          path: "/data/test"
