apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  selector:
    app: es
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 31345
  type: NodePort
---
apiVersion: apps/v1

kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: es
      track: stable
  template:
    metadata:
      labels:
        app: es
        track: stable
  
    spec:
      containers:
      - image: horcle/es
        name: es
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: volume
          mountPath: "/data/test"
  
      volumes:
      - name: volume
        hostPath:
          path: "/data/test"
