version: '2'

settings:

  conductor:
    base: 'ubuntu:16.04'
    volumes:
    - ${PWD}/temp-space:/tmp

  k8s_namespace:
    name: demo
    display_name: Ansible Container Demo 
    description: NLP-ADAPT demo 

defaults:
  POSTGRES_USER: django
  POSTGRES_PASSWORD: sesame
  POSTGRES_DB: django
  DJANGO_ROOT: /django
  DJANGO_USER: django
  DJANGO_PORT: 8080
  DJANGO_VENV: /venv
  NODE_USER: node
  NODE_HOME: /node
  NODE_ROOT: ''
  GULP_DEV_PORT: 8080

  NLPTAB_ROOT: /nlptab-webapp
  ES_ROOT: /elasticsearch-2.1.0
  JAVA_HOME: /usr/libexec/java_home
  NLPTAB_PORT: 8000
  ES_PORT: 9200
  TEST_SRC: ~/development/tools/elasticsearch-2.1.0
  TEST_HOME: /elastic_search

services:
  nlptab:
    from: 'ubuntu:16.04'
    environment:
      NLPTAB_URL: 'http://localhost:{{ NLPTAB_PORT }}'
    expose:
    - '{{ NLPTAB_PORT }}'
    working_dir: '{{ NLPTAB_ROOT }}'
    links:
    - elastic
    entrypoint: ['gulp webserver']
  elastic:
    from: 'ubuntu:16.04'
    working_dir: '{{ ES_ROOT }}'
    expose:
    - '{{ ES_PORT }}'
    command: ['/bin/elasticsearch']
    environment:
      JAVA_HOME: '{{ JAVA_HOME }}'

