apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: biomedicus-wf-    #name of workflow spec
spec:
  entrypoint: build          #invoke the build template
  volumes:
  - name: test-volume
    hostPath:
      path: /Users/gms/workspace/test # must match host directory in minikube; cannot be symlinked
  templates:
  - name: build              #name of template
    container:
      image: horcle/biomedicus
      imagePullPolicy: IfNotPresent
      command: ["/usr/share/biomedicus/bin/runCPE.sh"] 
      args: ["/usr/share/biomedicus/nlpie/PlainTextCPM_nlpie.xml"]
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false
      # resources:                #don't use too much resources
      #  limits:
      #    memory: 32Mi
      #    cpu: 100m
