apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: biomedicus-wf-    #name of workflow spec
spec:
  entrypoint: biomedicus-test          #invoke the build template
  volumes:
  - name: test-volume
    hostPath:
      path: /Users/gms/workspace/test # must match host directory in minikube; cannot be symlinked
  
  templates:

  - name: biomedicus-test
    steps:
       - - name: elastic-deployment
           template: elastic-server-d
       - - name: elastic-service
           template: elastic-server-s
       
       - - name: build 
           template: build-out
       - - name: package  
           template: package-out

       - - name: post
           template: post-data
           arguments:
             parameters: 
             - name: data
               value: 

  
  - name: elastic-server-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: es
        spec:
          selector:
            matchLabels:
              app: es
              track: stable
          template:
            metadata:
              labels:
                app: es
                track: stable
          
            spec:
              containers:
              - image: horcle/elastic
                imagePullPolicy: Never
                name: es
                ports:
                - containerPort: 9200
                - containerPort: 9300
                volumeMounts:
                - name: test-volume
                  mountPath: /data
                  readOnly: false  
              
              volumes:
              - name: test-volume
                hostPath:
                  path: /Users/gms/workspace/test 


  - name: elastic-server-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: es
          namespace: default
          labels:
            app: es

        spec:
          selector:
            app: es
          ports:
          - port: 9200
            targetPort: 9200
            nodePort: 31345
          type: NodePort
       

  - name: build-out
    container:
      image: horcle/biomedicus
      imagePullPolicy: Never
      command: ["/usr/share/biomedicus/bin/runCPE.sh"] 
      args: ["/usr/share/biomedicus/nlpie/PlainTextCPM_nlpie.xml"]
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false
      # resources:                #don't use too much resources
      #  limits:
      #    memory: 32Mi
      #    cpu: 100m
      
  - name:  package-out           
    container:
      image: horcle/biomedicus
      imagePullPolicy: Never
      command: [sh, -c]
      args: ["zip -r /data/biomedicus_out.zip /data/biomedicus_out"]
      outputs:
      artifacts:
      # generate hello-art artifact from /tmp/hello_world.txt
      # artifacts can be directories as well as files
      - name: biomedicus_out
        path: /data/biomedicus_out/biomedicus_out.zip
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: post-data 
    inputs:
        artifacts:
          # unpack the message input artifact
          # and put it at /tmp/message
        - name: biomedicus_out
          path: /data/biomedicus_out/biomedicus_out.zip
    container:
      image: horcle/elastic
      imagePullPolicy: Never
      command: [sh, -c]
      args: ["curl -sS -d /data/biomedicus_out/biomedicus_out.zip {{steps.elastic-server-s.ip}}:9200/_nlptab-systemindexmeta"]
      # args: ["curl -sS -d @- http://192.168.99.100:31345/_nlptab-systemindexmeta"]
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

