apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-adapt-wf-    #name of workflow spec
spec:
  entrypoint: nlp-adapt          #invoke the build template
  volumes:
  - name: test-volume
    hostPath:
      path: /Users/gregsilverman/workspace/test # must match host directory in minikube; cannot be symlinked
      # path: /Volumes/GrenziData/development/data
  
  templates:

  - name: nlp-adapt
    steps:
    - - name: elastic-deployment
        template: elastic-server-d
    - - name: elastic-service
        template: elastic-server-s

    - - name: nlptab-deployment
        template: nlptab-server-d
    - - name: nlptab-service
        template: nlptab-server-s
 
    - - name: biomedicus
    template: run-biomedicus

    - - name: metamap 
        template: run-metamap

    - - name: ctakes 
        template: run-ctakes

    - - name: clamp 
        template: run-clamp
  
  - name: elastic-server-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: es
        spec:
          selector:
            matchLabels:
              app: es
              track: stable
          template:
            metadata:
              labels:
                app: es
                track: stable
          
            spec:
              containers:
              - image: horcle/elastic
                imagePullPolicy: Never
                name: es
                ports:
                - containerPort: 9200
                - containerPort: 9300
                volumeMounts:
                - name: test-volume
                  mountPath: /data
                  readOnly: false  
              
              volumes:
              - name: test-volume
                hostPath:
                  path: /Users/gregsilverman/workspace/test 


  - name: elastic-server-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: es
          namespace: default
          labels:
            app: es

        spec:
          selector:
            app: es
          ports:
          - port: 9200
            targetPort: 9200
            nodePort: 31345
          type: NodePort
       
  - name: nlptab-server-d
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nlptab
        spec:
          selector:
            matchLabels:
              app: nlptab
              track: stable
          template:
            metadata:
              labels:
                app: nlptab
                track: stable
          
            spec:
              containers:
              - image: horcle/nlptab
                imagePullPolicy: Never
                name: nlptab
                ports:
                - containerPort: 8000
                volumeMounts:
                - name: test-volume
                  mountPath: /data
                  readOnly: false  
              
              volumes:
              - name: test-volume
                hostPath:
                  path: /Users/gregsilverman/workspace/test 


  - name: nlptab-server-s
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: nlptab
          namespace: default
          labels:
            app: nlptab

        spec:
          selector:
            app: nlptab
          ports:
          - port: 80
            targetPort: 8000
            nodePort: 31234
          type: NodePort

  - name: run-biomedicus
    container:
      image: horcle/biomedicus
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/biomedicus/scripts/run_biomedicus.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-metamap
    container:
      image: horcle/metamap
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/public_mm/scripts/run_metamap.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-ctakes
    container:
      image: horcle/ctakes
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/ctakes/scripts/run_ctakes.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-clamp
    container:
      image: horcle/clamp
      imagePullPolicy: Never
      tty: true
      stdin: true
      command: ["/usr/share/clamp/scripts/run_clamp.sh"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

