# ansible-playbook test_ctakes.yml --user=gms --ask-sudo-pass
---
- hosts: 127.0.0.1
  connection: local
  #sudo: true
  vars:
    download_dir: ~/development/nlp/test
    ctakes_dir: ~/development/nlp/test
    path_test: ~/development/nlp/test
    ctakes_url: http://mirror.stjschools.org/public/apache//ctakes/ctakes-4.0.0/apache-ctakes-4.0.0-bin.tar.gz
    ctakes_src: ~/development/nlp/test/apache-ctakes-4.0.0-bin.tar.gz
    env_dir: /etc/profile
    bash_profile: ~/.bash_profile
    umls_user: horcle
    umls_pw: ix2244r
    user: gms
  tasks:
  - name: Prepare Install folder
    file: path={{download_dir}} state=directory
    become: yes
    become_user: gms
  - name: Download cTAKES
    get_url: url={{ctakes_url}} dest={{download_dir}}
    become: yes
    become_user: gms
  - name: Extract cTAKES
    unarchive: src={{ctakes_src}}
               dest={{ctakes_dir}}
    become: yes
    become_user: gms
  - name: Update bash_profile
    blockinfile:
      dest: "{{ bash_profile }}"
      block: |
        export ctakes_umlsuser={{user}}
        export PATH="{{path_test}}:$PATH"      
      marker: '## {mark} ANSIBLE MANAGED BLOCK - cTAKES'
      insertbefore: EOF
      state: present
