# ansible-playbook test_ctakes.yml --user=gms --ask-sudo-pass
---
- hosts: 127.0.0.1
  connection: local
  #sudo: true
  vars:
    path_test: ../amicus-distribution
    amicus_url: https://github.com/nlpie/amicus.git
    java_home: /usr/lib/jvm/java-8-openjdk-amd64
    user: gms
  tasks:
  - git:
      repo: "{{amicus_url}}"
      dest: "{{path_test}}"
      clone: no
      update: no
